### ISSUE TITLE
How to obtain a resource key

### ISSUE THREAD

**Issue by kaiiyer** [ibm-cloud-docs/AnalyticsEngine#14]
While adding the Analytics Engine service to my project I encountered across this:
"Selected Analytics Engine instance does not have a resource key. Please select another instance, or contact the instance owner."

**Comment by gabydreckschmidt** [comment]
@kaiiyer 
This has been fixed. The error message now also contains this link https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/faq.html#no-resource-key which explains what needs to be done to obtain the resources key.
