### ISSUE TITLE
Livy do not support '{"file": "local: parameter for .py files and the file needs to be in HDFS

### ISSUE THREAD

**Issue by charles2588** [ibm-cloud-docs/AnalyticsEngine#16]
https://cloud.ibm.com/docs/services/AnalyticsEngine?topic=AnalyticsEngine-livy-api

The file parameter is not supported for local .py files.
You would to put your .py file is in HDFS to make it work with the Livy.

So from the cluster first you do hadop fs -put /usr/hdp/current/spark2-client/examples/src/main/python/pi.py /user/clsadmin

and then run

curl -u "clsadmin:asdfasdf" -H 'Content-Type: application/json' -H 'X-Requested-By: livy' -d '{"file": "/user/clsaddmin/pi.py", "proxyUser":"clsadmin"}' "https://chs-asdf-asdf-mn001.us-south.ae.appdomain.cloud:8443/gateway/default/livy/v1/batches"

**Comment by gabydreckschmidt** [comment]
This was corrected. 
See https://cloud.ibm.com/docs/AnalyticsEngine?topic=AnalyticsEngine-livy-api#submit-a-spark-job-with-a-local-python-file
