### ISSUE TITLE
Need to document :- Hive view no longer supported from Analytics Engine 1.2

### ISSUE THREAD

**Issue by charles2588** [ibm-cloud-docs/AnalyticsEngine#17]
Hive view is no longer supported from AE 1.2.

An alternative to this is to use the Squirrel JDBC client. You can refer to this one https://medium.com/ibm-analytics/ibm-analytics-engine-how-to-connect-squirrel-with-jdbc-to-hive-on-ibm-analytics-engine-a23866961a63

**Comment by gabydreckschmidt** [comment]
@charles2588 Has been documented. See:

- https://cloud.ibm.com/docs/services/AnalyticsEngine?topic=AnalyticsEngine-release-notes
- https://cloud.ibm.com/docs/services/AnalyticsEngine?topic=AnalyticsEngine-unsupported-operations#hive-view-not-supported
