### ISSUE TITLE
Update FAQs section regarding lite plan

### ISSUE THREAD

**Issue by wksuser** [ibm-cloud-docs/AnalyticsEngine#18]
https://cloud.ibm.com/docs/services/AnalyticsEngine?topic=AnalyticsEngine-general-faqs#free-usage

> Is there a free usage tier to try IBM Analytics Engine?
> 
> Yes, we provide the Lite plan which can be used free of charge. Apart from this, as a new IBM Cloud user, you are also entitled to $200 in credit that can be used against IBM Analytics Engine or any service on IBM Cloud.
> How does the Lite plan work?
> 
> The Lite plan provides 50 node-hours of free IBM Analytics Engine usage. One cluster can be provisioned every 30 days. After the 50 node-hours are exhausted, you can upgrade to a paid plan within 24 hours to continue using the same cluster. If you do not upgrade within 24 hours, the cluster will be deleted and you have to provision a new one after the 30 day limit has passed.
> 
> Depending on the size of your cluster, actual hours of use might vary. For instance, a cluster with 1 master and 3 data nodes (4 nodes in total) will run for 12.5 hours on the clock (50 hours/4 nodes). However, a cluster with 1 master and 1 data node (2 nodes in total) will run for 25 hours on the clock (50 hours/2 nodes). The node-hours cannot be paused, for example, you cannot use 10 node-hours, pause, and then come back and use the remaining 40 node-hours.

**Comment by gabydreckschmidt** [comment]
The doc is clear that yes there is but only if you explicitly sign up for it. This is to avoid misuse.
