### ISSUE TITLE
Advance provisioning options does not work Postgressql as Metastore for hive

### ISSUE THREAD

**Issue by charles2588** [ibm-cloud-docs/AnalyticsEngine#19]
Add known issue:- Advance provisioning does not support Postgressql as Metastore for hive.

Provisioning would fail.

Workaround:-

Remove the metastore configuration parameters from advance provisioning options and provision without them.
Once it is provisioned, you can use customization script to setup the metastore.
Please follow this link:-
https://cloud.ibm.com/docs/services/AnalyticsEngine?topic=AnalyticsEngine-cust-examples#postgres-metastore

**Comment by gabydreckschmidt** [comment]
Added new known issue with a work around
