### ISSUE TITLE
The page Accessing objects in Object Storage is very confusing

### ISSUE THREAD

**Issue by andersonm-1** [ibm-cloud-docs/AnalyticsEngine#20]
There is no explanation of what is a servicename in the following:

> 
> To access data objects in an Object Storage bucket, use the following URI:
`cos://<bucket_name>.<servicename>/<object_name>`

You should take the explanation from Stocator documentation:
`where <bucket> is object storage bucket and <service> identifies configuration group entry.`

And then there goes an even more confusing example:

`cos://b1.**firstbucket**/detail.txt`

In the example the "configuration group entry" is called "firstbucket", and it turns out that the bucket name is "b1".

**Comment by vmw-andersonm** [comment]
A link to the page:
https://cloud.ibm.com/docs/AnalyticsEngine?topic=AnalyticsEngine-access-objs-in-cos

**Comment by vmw-andersonm** [comment]
@gabydreckschmidt @mrmadira

**Comment by mrmadira** [comment]
I agree - This was in my list
Thankyou for bringing this back to the top.

**Comment by gabydreckschmidt** [comment]
Added more descriptive information and used the same examples across all COS topics
