### ISSUE TITLE
This doc that explains how to configure Ambari to use object storage does not explain how to verify

### ISSUE THREAD

**Issue by sshankarn** [ibm-cloud-docs/AnalyticsEngine#21]
This doc that explains how to configure Ambari to use object storage does not explain how to verify. It misses one screen snapshot of what to expect after you do all the things as stated in this doc. That is verification and validation. Or in other words, OK we did all this, will the object storage show up in the Fie browser of Ambari? How to verify if this working at all as we added apikey and endpoint.

**Comment by gabydreckschmidt** [comment]
Added verification step
